[package]
name = "mallee-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mallee"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
mallee-core = { path = "../mallee-core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
